# -*- mode: ruby -*-
# vi: set ft=ruby :

SERVER_MEMORY = "512"
VMNAME = "pgfilter_vm"

PGPORT = "5432"
PGUSER = "dbadmin"
PGPASSWORD = "devved"
PGDATABASE = "dvdrental"
PGVERSION = "13"
NODE_VER = "16.x"
DB_DIR="/home/vagrant/pg_restore_filter/vagrant/pgscripts/"


Vagrant.configure("2") do |config|

	config.vm.provider "virtualbox" do |vb, orvb|
		orvb.vm.synced_folder '../', '/home/vagrant/pgfilter', create:true, :mount_options => ['dmode=775', 'fmode=777']
		orvb.vm.network "private_network", ip: "192.168.56.26"
		vb.customize ["modifyvm", :id, "--memory", SERVER_MEMORY]
		vb.name = VMNAME
	end

	config.vm.define "pgfilter" do |pgfilter|
		pgfilter.vm.box = "generic/ubuntu2004"
		pgfilter.vm.hostname = "pgfilter"
		pgfilter.vm.provision :shell do |s|
			s.path = "provision.sh"
			s.env = {
				"PGPORT" => PGPORT,
				"PGUSER" => PGUSER,
				"PGPASSWORD" => PGPASSWORD,
				"PGDATABASE" => PGDATABASE,
				"PGVERSION" => PGVERSION,
				"NODE_VER" => NODE_VER,
			}
		end
	end

end
